timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect
1542690585983,304,Get Collections,200,OK,Thread Group 1-1,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,304,0,27
1542690586288,5,Get One Collection,200,OK,Thread Group 1-1,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690585895,309,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-1,,true,,1020,365,1,1,null,309,89,27
1542690586294,4,Get Account Info,200,OK,Thread Group 1-1,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690586293,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-1,,true,,565,161,1,1,null,4,1,0
1542690586404,14,Get Collections,200,OK,Thread Group 1-2,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,14,0,2
1542690586420,14,Get One Collection,200,OK,Thread Group 1-2,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690586401,28,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-2,,true,,1020,365,1,1,null,28,6,2
1542690586435,12,Get Account Info,200,OK,Thread Group 1-2,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,12,0,0
1542690586435,12,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-2,,true,,565,161,1,1,null,12,0,0
1542690586895,7,Get Collections,200,OK,Thread Group 1-3,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,2
1542690586902,5,Get One Collection,200,OK,Thread Group 1-3,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690586894,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-3,,true,,1020,365,1,1,null,12,1,2
1542690586907,4,Get Account Info,200,OK,Thread Group 1-3,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690586907,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-3,,true,,565,161,1,1,null,4,0,0
1542690587415,6,Get Collections,200,OK,Thread Group 1-4,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,2
1542690587422,5,Get One Collection,200,OK,Thread Group 1-4,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690587414,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-4,,true,,1020,365,1,1,null,10,2,2
1542690587427,4,Get Account Info,200,OK,Thread Group 1-4,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690587427,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-4,,true,,565,161,1,1,null,4,0,0
1542690587915,7,Get Collections,200,OK,Thread Group 1-5,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,3
1542690587923,5,Get One Collection,200,OK,Thread Group 1-5,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690587914,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-5,,true,,1020,365,1,1,null,12,2,3
1542690587928,4,Get Account Info,200,OK,Thread Group 1-5,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690587928,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-5,,true,,565,161,1,1,null,4,0,0
1542690588416,17,Get Collections,200,OK,Thread Group 1-6,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,17,0,5
1542690588434,14,Get One Collection,200,OK,Thread Group 1-6,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690588415,31,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-6,,true,,1020,365,1,1,null,31,3,5
1542690588449,11,Get Account Info,200,OK,Thread Group 1-6,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,11,0,0
1542690588449,11,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-6,,true,,565,161,1,1,null,11,1,0
1542690588916,14,Get Collections,200,OK,Thread Group 1-7,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,14,0,2
1542690588931,16,Get One Collection,200,OK,Thread Group 1-7,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,16,0,0
1542690588914,30,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-7,,true,,1020,365,1,1,null,30,4,2
1542690588948,8,Get Account Info,200,OK,Thread Group 1-7,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,8,0,0
1542690588948,8,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-7,,true,,565,161,1,1,null,8,0,0
1542690589415,6,Get Collections,200,OK,Thread Group 1-8,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,1
1542690589421,5,Get One Collection,200,OK,Thread Group 1-8,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690589413,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-8,,true,,1020,365,1,1,null,11,2,1
1542690589426,4,Get Account Info,200,OK,Thread Group 1-8,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690589426,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-8,,true,,565,161,1,1,null,4,0,0
1542690589916,6,Get Collections,200,OK,Thread Group 1-9,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,2
1542690589922,5,Get One Collection,200,OK,Thread Group 1-9,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690589914,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-9,,true,,1020,365,1,1,null,11,2,2
1542690589928,3,Get Account Info,200,OK,Thread Group 1-9,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690589927,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-9,,true,,565,161,1,1,null,3,1,0
1542690590416,8,Get Collections,200,OK,Thread Group 1-10,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,8,0,2
1542690590425,5,Get One Collection,200,OK,Thread Group 1-10,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690590415,13,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-10,,true,,1020,365,1,1,null,12,2,2
1542690590430,3,Get Account Info,200,OK,Thread Group 1-10,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690590430,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-10,,true,,565,161,1,1,null,3,0,0
1542690590916,10,Get Collections,200,OK,Thread Group 1-11,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690590927,5,Get One Collection,200,OK,Thread Group 1-11,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690590915,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-11,,true,,1020,365,1,1,null,14,2,2
1542690590932,4,Get Account Info,200,OK,Thread Group 1-11,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690590932,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-11,,true,,565,161,1,1,null,4,0,0
1542690591417,14,Get Collections,200,OK,Thread Group 1-12,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,14,0,2
1542690591432,8,Get One Collection,200,OK,Thread Group 1-12,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,7,0,0
1542690591416,22,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-12,,true,,1020,365,1,1,null,21,2,2
1542690591440,4,Get Account Info,200,OK,Thread Group 1-12,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690591440,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-12,,true,,565,161,1,1,null,4,0,0
1542690591916,10,Get Collections,200,OK,Thread Group 1-13,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690591926,5,Get One Collection,200,OK,Thread Group 1-13,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690591915,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-13,,true,,1020,365,1,1,null,15,1,2
1542690591932,3,Get Account Info,200,OK,Thread Group 1-13,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690591931,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-13,,true,,565,161,1,1,null,3,1,0
1542690592414,13,Get Collections,200,OK,Thread Group 1-14,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690592428,8,Get One Collection,200,OK,Thread Group 1-14,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,8,0,0
1542690592413,21,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-14,,true,,1020,365,1,1,null,21,2,2
1542690592436,4,Get Account Info,200,OK,Thread Group 1-14,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690592436,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-14,,true,,565,161,1,1,null,4,0,0
1542690592915,11,Get Collections,200,OK,Thread Group 1-15,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,11,0,2
1542690592926,6,Get One Collection,200,OK,Thread Group 1-15,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,6,0,0
1542690592914,17,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-15,,true,,1020,365,1,1,null,17,1,2
1542690592932,3,Get Account Info,200,OK,Thread Group 1-15,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690592932,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-15,,true,,565,161,1,1,null,3,0,0
1542690593419,6,Get Collections,200,OK,Thread Group 1-16,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,1
1542690593425,5,Get One Collection,200,OK,Thread Group 1-16,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690593417,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-16,,true,,1020,365,1,1,null,11,2,1
1542690593430,4,Get Account Info,200,OK,Thread Group 1-16,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690593430,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-16,,true,,565,161,1,1,null,4,0,0
1542690593923,14,Get Collections,200,OK,Thread Group 1-17,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690593937,10,Get One Collection,200,OK,Thread Group 1-17,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,10,0,0
1542690593922,24,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-17,,true,,1020,365,1,1,null,23,1,2
1542690593947,4,Get Account Info,200,OK,Thread Group 1-17,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690593947,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-17,,true,,565,161,1,1,null,4,0,0
1542690594426,11,Get Collections,200,OK,Thread Group 1-18,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,11,0,2
1542690594437,5,Get One Collection,200,OK,Thread Group 1-18,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690594425,16,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-18,,true,,1020,365,1,1,null,16,1,2
1542690594442,4,Get Account Info,200,OK,Thread Group 1-18,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690594442,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-18,,true,,565,161,1,1,null,4,0,0
1542690594931,10,Get Collections,200,OK,Thread Group 1-19,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690594941,5,Get One Collection,200,OK,Thread Group 1-19,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690594930,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-19,,true,,1020,365,1,1,null,15,1,2
1542690594946,4,Get Account Info,200,OK,Thread Group 1-19,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690594946,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-19,,true,,565,161,1,1,null,4,0,0
1542690595435,13,Get Collections,200,OK,Thread Group 1-20,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690595449,13,Get One Collection,200,OK,Thread Group 1-20,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690595433,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-20,,true,,1020,365,1,1,null,26,4,2
1542690595463,10,Get Account Info,200,OK,Thread Group 1-20,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,10,0,0
1542690595463,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-20,,true,,565,161,1,1,null,10,0,0
1542690595936,10,Get Collections,200,OK,Thread Group 1-21,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690595947,4,Get One Collection,200,OK,Thread Group 1-21,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690595935,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-21,,true,,1020,365,1,1,null,14,3,2
1542690595952,3,Get Account Info,200,OK,Thread Group 1-21,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690595952,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-21,,true,,565,161,1,1,null,3,0,0
1542690596436,7,Get Collections,200,OK,Thread Group 1-22,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,1
1542690596443,5,Get One Collection,200,OK,Thread Group 1-22,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690596434,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-22,,true,,1020,365,1,1,null,12,2,1
1542690596448,4,Get Account Info,200,OK,Thread Group 1-22,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690596448,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-22,,true,,565,161,1,1,null,4,0,0
1542690596935,13,Get Collections,200,OK,Thread Group 1-23,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690596949,14,Get One Collection,200,OK,Thread Group 1-23,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690596934,27,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-23,,true,,1020,365,1,1,null,26,3,2
1542690596964,9,Get Account Info,200,OK,Thread Group 1-23,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690596964,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-23,,true,,565,161,1,1,null,9,0,0
1542690597439,10,Get Collections,200,OK,Thread Group 1-24,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690597450,4,Get One Collection,200,OK,Thread Group 1-24,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690597437,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-24,,true,,1020,365,1,1,null,14,3,1
1542690597455,3,Get Account Info,200,OK,Thread Group 1-24,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690597454,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-24,,true,,565,161,1,1,null,3,1,0
1542690597941,10,Get Collections,200,OK,Thread Group 1-25,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690597951,5,Get One Collection,200,OK,Thread Group 1-25,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690597939,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-25,,true,,1020,365,1,1,null,15,2,1
1542690597956,4,Get Account Info,200,OK,Thread Group 1-25,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690597956,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-25,,true,,565,161,1,1,null,4,0,0
1542690598443,10,Get Collections,200,OK,Thread Group 1-26,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690598453,5,Get One Collection,200,OK,Thread Group 1-26,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690598442,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-26,,true,,1020,365,1,1,null,15,1,2
1542690598458,5,Get Account Info,200,OK,Thread Group 1-26,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,5,0,0
1542690598458,5,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-26,,true,,565,161,1,1,null,5,0,0
1542690598946,10,Get Collections,200,OK,Thread Group 1-27,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690598956,5,Get One Collection,200,OK,Thread Group 1-27,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690598944,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-27,,true,,1020,365,1,1,null,15,2,1
1542690598961,4,Get Account Info,200,OK,Thread Group 1-27,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690598961,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-27,,true,,565,161,1,1,null,4,0,0
1542690599455,10,Get Collections,200,OK,Thread Group 1-28,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690599465,5,Get One Collection,200,OK,Thread Group 1-28,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690599453,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-28,,true,,1020,365,1,1,null,15,2,1
1542690599470,3,Get Account Info,200,OK,Thread Group 1-28,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690599470,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-28,,true,,565,161,1,1,null,3,1,0
1542690599960,9,Get Collections,200,OK,Thread Group 1-29,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,2
1542690599969,6,Get One Collection,200,OK,Thread Group 1-29,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,6,0,0
1542690599959,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-29,,true,,1020,365,1,1,null,15,1,2
1542690599975,3,Get Account Info,200,OK,Thread Group 1-29,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690599975,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-29,,true,,565,161,1,1,null,3,0,0
1542690600473,10,Get Collections,200,OK,Thread Group 1-30,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690600484,5,Get One Collection,200,OK,Thread Group 1-30,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690600472,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-30,,true,,1020,365,1,1,null,15,2,2
1542690600489,3,Get Account Info,200,OK,Thread Group 1-30,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690600489,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-30,,true,,565,161,1,1,null,3,0,0
1542690600974,13,Get Collections,200,OK,Thread Group 1-31,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690600988,13,Get One Collection,200,OK,Thread Group 1-31,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690600973,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-31,,true,,1020,365,1,1,null,26,3,2
1542690601002,10,Get Account Info,200,OK,Thread Group 1-31,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690601002,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-31,,true,,565,161,1,1,null,9,0,0
1542690601480,13,Get Collections,200,OK,Thread Group 1-32,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690601494,15,Get One Collection,200,OK,Thread Group 1-32,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690601478,28,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-32,,true,,1020,365,1,1,null,27,3,1
1542690601509,10,Get Account Info,200,OK,Thread Group 1-32,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,10,0,0
1542690601509,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-32,,true,,565,161,1,1,null,10,1,0
1542690601984,6,Get Collections,200,OK,Thread Group 1-33,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,2
1542690601990,5,Get One Collection,200,OK,Thread Group 1-33,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690601982,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-33,,true,,1020,365,1,1,null,11,2,2
1542690601995,3,Get Account Info,200,OK,Thread Group 1-33,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690601995,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-33,,true,,565,161,1,1,null,3,1,0
1542690602490,13,Get Collections,200,OK,Thread Group 1-34,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690602504,13,Get One Collection,200,OK,Thread Group 1-34,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690602488,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-34,,true,,1020,365,1,1,null,26,3,1
1542690602518,10,Get Account Info,200,OK,Thread Group 1-34,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,10,0,0
1542690602517,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-34,,true,,565,161,1,1,null,10,1,0
1542690602993,15,Get Collections,200,OK,Thread Group 1-35,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,15,0,2
1542690603009,14,Get One Collection,200,OK,Thread Group 1-35,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690602992,29,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-35,,true,,1020,365,1,1,null,29,2,2
1542690603024,10,Get Account Info,200,OK,Thread Group 1-35,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690603024,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-35,,true,,565,161,1,1,null,9,0,0
1542690603496,14,Get Collections,200,OK,Thread Group 1-36,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,14,0,1
1542690603511,13,Get One Collection,200,OK,Thread Group 1-36,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690603494,27,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-36,,true,,1020,365,1,1,null,27,4,1
1542690603525,10,Get Account Info,200,OK,Thread Group 1-36,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,10,0,0
1542690603525,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-36,,true,,565,161,1,1,null,10,1,0
1542690603996,7,Get Collections,200,OK,Thread Group 1-37,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,1
1542690604003,5,Get One Collection,200,OK,Thread Group 1-37,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690603995,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-37,,true,,1020,365,1,1,null,12,1,1
1542690604008,4,Get Account Info,200,OK,Thread Group 1-37,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690604008,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-37,,true,,565,161,1,1,null,4,0,0
1542690604497,10,Get Collections,200,OK,Thread Group 1-38,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690604507,5,Get One Collection,200,OK,Thread Group 1-38,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690604496,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-38,,true,,1020,365,1,1,null,15,1,2
1542690604512,4,Get Account Info,200,OK,Thread Group 1-38,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690604512,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-38,,true,,565,161,1,1,null,4,0,0
1542690604996,6,Get Collections,200,OK,Thread Group 1-39,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,2
1542690605002,5,Get One Collection,200,OK,Thread Group 1-39,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690604995,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-39,,true,,1020,365,1,1,null,11,1,2
1542690605007,4,Get Account Info,200,OK,Thread Group 1-39,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690605007,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-39,,true,,565,161,1,1,null,4,0,0
1542690605497,13,Get Collections,200,OK,Thread Group 1-40,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690605510,15,Get One Collection,200,OK,Thread Group 1-40,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,15,0,0
1542690605495,28,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-40,,true,,1020,365,1,1,null,28,2,1
1542690605526,11,Get Account Info,200,OK,Thread Group 1-40,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,11,0,0
1542690605525,11,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-40,,true,,565,161,1,1,null,11,1,0
1542690605999,13,Get Collections,200,OK,Thread Group 1-41,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690606013,13,Get One Collection,200,OK,Thread Group 1-41,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690605997,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-41,,true,,1020,365,1,1,null,26,3,1
1542690606027,10,Get Account Info,200,OK,Thread Group 1-41,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690606027,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-41,,true,,565,161,1,1,null,9,0,0
1542690606500,11,Get Collections,200,OK,Thread Group 1-42,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,11,0,2
1542690606511,4,Get One Collection,200,OK,Thread Group 1-42,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690606499,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-42,,true,,1020,365,1,1,null,15,2,2
1542690606516,4,Get Account Info,200,OK,Thread Group 1-42,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690606516,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-42,,true,,565,161,1,1,null,3,0,0
1542690607005,8,Get Collections,200,OK,Thread Group 1-43,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,8,0,2
1542690607013,6,Get One Collection,200,OK,Thread Group 1-43,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,6,0,0
1542690607004,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-43,,true,,1020,365,1,1,null,14,1,2
1542690607019,4,Get Account Info,200,OK,Thread Group 1-43,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690607019,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-43,,true,,565,161,1,1,null,4,0,0
1542690607507,9,Get Collections,200,OK,Thread Group 1-44,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690607516,5,Get One Collection,200,OK,Thread Group 1-44,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690607505,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-44,,true,,1020,365,1,1,null,14,2,1
1542690607521,4,Get Account Info,200,OK,Thread Group 1-44,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690607521,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-44,,true,,565,161,1,1,null,4,0,0
1542690608008,10,Get Collections,200,OK,Thread Group 1-45,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690608018,5,Get One Collection,200,OK,Thread Group 1-45,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690608007,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-45,,true,,1020,365,1,1,null,15,1,1
1542690608023,4,Get Account Info,200,OK,Thread Group 1-45,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690608023,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-45,,true,,565,161,1,1,null,4,0,0
1542690608508,14,Get Collections,200,OK,Thread Group 1-46,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,14,0,2
1542690608523,9,Get One Collection,200,OK,Thread Group 1-46,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,9,0,0
1542690608507,23,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-46,,true,,1020,365,1,1,null,23,2,2
1542690608532,4,Get Account Info,200,OK,Thread Group 1-46,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690608532,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-46,,true,,565,161,1,1,null,4,0,0
1542690609010,9,Get Collections,200,OK,Thread Group 1-47,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690609019,5,Get One Collection,200,OK,Thread Group 1-47,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690609009,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-47,,true,,1020,365,1,1,null,14,1,1
1542690609024,3,Get Account Info,200,OK,Thread Group 1-47,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690609024,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-47,,true,,565,161,1,1,null,3,0,0
1542690609510,8,Get Collections,200,OK,Thread Group 1-48,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,8,0,2
1542690609518,4,Get One Collection,200,OK,Thread Group 1-48,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690609509,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-48,,true,,1020,365,1,1,null,12,1,2
1542690609523,3,Get Account Info,200,OK,Thread Group 1-48,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690609522,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-48,,true,,565,161,1,1,null,3,2,0
1542690610013,10,Get Collections,200,OK,Thread Group 1-49,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690610023,5,Get One Collection,200,OK,Thread Group 1-49,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690610012,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-49,,true,,1020,365,1,1,null,15,1,2
1542690610028,4,Get Account Info,200,OK,Thread Group 1-49,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690610028,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-49,,true,,565,161,1,1,null,4,0,0
1542690610514,9,Get Collections,200,OK,Thread Group 1-50,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,2
1542690610523,5,Get One Collection,200,OK,Thread Group 1-50,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690610513,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-50,,true,,1020,365,1,1,null,13,1,2
1542690610528,3,Get Account Info,200,OK,Thread Group 1-50,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690610528,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-50,,true,,565,161,1,1,null,3,0,0
1542690611023,10,Get Collections,200,OK,Thread Group 1-51,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690611033,5,Get One Collection,200,OK,Thread Group 1-51,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690611022,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-51,,true,,1020,365,1,1,null,15,2,2
1542690611039,3,Get Account Info,200,OK,Thread Group 1-51,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690611039,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-51,,true,,565,161,1,1,null,3,0,0
1542690611522,7,Get Collections,200,OK,Thread Group 1-52,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,1
1542690611529,5,Get One Collection,200,OK,Thread Group 1-52,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690611521,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-52,,true,,1020,365,1,1,null,11,1,1
1542690611534,3,Get Account Info,200,OK,Thread Group 1-52,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690611534,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-52,,true,,565,161,1,1,null,3,1,0
1542690612025,10,Get Collections,200,OK,Thread Group 1-53,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690612035,4,Get One Collection,200,OK,Thread Group 1-53,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690612023,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-53,,true,,1020,365,1,1,null,14,2,1
1542690612040,3,Get Account Info,200,OK,Thread Group 1-53,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690612039,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-53,,true,,565,161,1,1,null,3,1,0
1542690612524,7,Get Collections,200,OK,Thread Group 1-54,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,2
1542690612531,5,Get One Collection,200,OK,Thread Group 1-54,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690612523,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-54,,true,,1020,365,1,1,null,12,1,2
1542690612537,3,Get Account Info,200,OK,Thread Group 1-54,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690612536,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-54,,true,,565,161,1,1,null,3,1,0
1542690613024,8,Get Collections,200,OK,Thread Group 1-55,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,8,0,2
1542690613033,4,Get One Collection,200,OK,Thread Group 1-55,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690613023,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-55,,true,,1020,365,1,1,null,12,2,2
1542690613038,3,Get Account Info,200,OK,Thread Group 1-55,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690613038,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-55,,true,,565,161,1,1,null,3,0,0
1542690613530,9,Get Collections,200,OK,Thread Group 1-56,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690613539,4,Get One Collection,200,OK,Thread Group 1-56,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690613529,13,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-56,,true,,1020,365,1,1,null,13,2,1
1542690613544,3,Get Account Info,200,OK,Thread Group 1-56,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690613544,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-56,,true,,565,161,1,1,null,3,0,0
1542690614035,10,Get Collections,200,OK,Thread Group 1-57,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690614045,5,Get One Collection,200,OK,Thread Group 1-57,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690614033,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-57,,true,,1020,365,1,1,null,15,2,1
1542690614050,4,Get Account Info,200,OK,Thread Group 1-57,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690614050,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-57,,true,,565,161,1,1,null,3,0,0
1542690614537,10,Get Collections,200,OK,Thread Group 1-58,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690614547,5,Get One Collection,200,OK,Thread Group 1-58,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690614535,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-58,,true,,1020,365,1,1,null,15,2,1
1542690614552,3,Get Account Info,200,OK,Thread Group 1-58,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690614552,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-58,,true,,565,161,1,1,null,3,0,0
1542690615036,9,Get Collections,200,OK,Thread Group 1-59,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690615045,5,Get One Collection,200,OK,Thread Group 1-59,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690615034,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-59,,true,,1020,365,1,1,null,14,2,1
1542690615051,3,Get Account Info,200,OK,Thread Group 1-59,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690615050,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-59,,true,,565,161,1,1,null,3,1,0
1542690615542,11,Get Collections,200,OK,Thread Group 1-60,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,11,0,2
1542690615553,4,Get One Collection,200,OK,Thread Group 1-60,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690615541,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-60,,true,,1020,365,1,1,null,15,1,2
1542690615558,3,Get Account Info,200,OK,Thread Group 1-60,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690615557,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-60,,true,,565,161,1,1,null,3,1,0
1542690616042,7,Get Collections,200,OK,Thread Group 1-61,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,3
1542690616049,5,Get One Collection,200,OK,Thread Group 1-61,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690616041,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-61,,true,,1020,365,1,1,null,12,1,3
1542690616054,4,Get Account Info,200,OK,Thread Group 1-61,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690616054,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-61,,true,,565,161,1,1,null,3,0,0
1542690616542,10,Get Collections,200,OK,Thread Group 1-62,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690616552,5,Get One Collection,200,OK,Thread Group 1-62,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690616541,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-62,,true,,1020,365,1,1,null,15,1,2
1542690616557,4,Get Account Info,200,OK,Thread Group 1-62,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690616557,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-62,,true,,565,161,1,1,null,4,0,0
1542690617042,9,Get Collections,200,OK,Thread Group 1-63,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690617051,5,Get One Collection,200,OK,Thread Group 1-63,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690617041,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-63,,true,,1020,365,1,1,null,14,1,1
1542690617056,3,Get Account Info,200,OK,Thread Group 1-63,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690617056,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-63,,true,,565,161,1,1,null,3,0,0
1542690617543,10,Get Collections,200,OK,Thread Group 1-64,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690617553,5,Get One Collection,200,OK,Thread Group 1-64,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690617542,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-64,,true,,1020,365,1,1,null,15,1,1
1542690617558,4,Get Account Info,200,OK,Thread Group 1-64,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690617558,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-64,,true,,565,161,1,1,null,4,0,0
1542690618044,10,Get Collections,200,OK,Thread Group 1-65,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690618054,5,Get One Collection,200,OK,Thread Group 1-65,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690618043,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-65,,true,,1020,365,1,1,null,15,1,1
1542690618059,4,Get Account Info,200,OK,Thread Group 1-65,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690618059,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-65,,true,,565,161,1,1,null,4,0,0
1542690618546,9,Get Collections,200,OK,Thread Group 1-66,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690618556,4,Get One Collection,200,OK,Thread Group 1-66,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690618545,13,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-66,,true,,1020,365,1,1,null,13,2,1
1542690618560,3,Get Account Info,200,OK,Thread Group 1-66,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690618560,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-66,,true,,565,161,1,1,null,3,0,0
1542690619048,9,Get Collections,200,OK,Thread Group 1-67,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,9,0,1
1542690619057,5,Get One Collection,200,OK,Thread Group 1-67,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690619046,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-67,,true,,1020,365,1,1,null,14,2,1
1542690619062,3,Get Account Info,200,OK,Thread Group 1-67,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690619062,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-67,,true,,565,161,1,1,null,3,0,0
1542690619548,10,Get Collections,200,OK,Thread Group 1-68,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690619558,5,Get One Collection,200,OK,Thread Group 1-68,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690619547,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-68,,true,,1020,365,1,1,null,15,1,1
1542690619563,4,Get Account Info,200,OK,Thread Group 1-68,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690619563,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-68,,true,,565,161,1,1,null,4,0,0
1542690620049,7,Get Collections,200,OK,Thread Group 1-69,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,2
1542690620056,4,Get One Collection,200,OK,Thread Group 1-69,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690620048,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-69,,true,,1020,365,1,1,null,10,1,2
1542690620061,3,Get Account Info,200,OK,Thread Group 1-69,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690620060,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-69,,true,,565,161,1,1,null,3,1,0
1542690620549,12,Get Collections,200,OK,Thread Group 1-70,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,12,0,1
1542690620562,12,Get One Collection,200,OK,Thread Group 1-70,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,12,0,0
1542690620548,24,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-70,,true,,1020,365,1,1,null,24,3,1
1542690620575,8,Get Account Info,200,OK,Thread Group 1-70,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,8,0,0
1542690620575,8,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-70,,true,,565,161,1,1,null,8,1,0
1542690621049,10,Get Collections,200,OK,Thread Group 1-71,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690621059,5,Get One Collection,200,OK,Thread Group 1-71,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690621048,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-71,,true,,1020,365,1,1,null,15,1,1
1542690621064,6,Get Account Info,200,OK,Thread Group 1-71,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,6,0,0
1542690621064,6,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-71,,true,,565,161,1,1,null,6,1,0
1542690621555,8,Get Collections,200,OK,Thread Group 1-72,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,8,0,2
1542690621563,4,Get One Collection,200,OK,Thread Group 1-72,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690621554,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-72,,true,,1020,365,1,1,null,12,1,2
1542690621568,3,Get Account Info,200,OK,Thread Group 1-72,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690621568,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-72,,true,,565,161,1,1,null,3,0,0
1542690622055,10,Get Collections,200,OK,Thread Group 1-73,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690622065,5,Get One Collection,200,OK,Thread Group 1-73,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690622054,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-73,,true,,1020,365,1,1,null,15,1,2
1542690622070,4,Get Account Info,200,OK,Thread Group 1-73,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690622070,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-73,,true,,565,161,1,1,null,4,0,0
1542690622559,7,Get Collections,200,OK,Thread Group 1-74,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,1
1542690622566,5,Get One Collection,200,OK,Thread Group 1-74,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690622557,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-74,,true,,1020,365,1,1,null,12,2,1
1542690622571,3,Get Account Info,200,OK,Thread Group 1-74,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690622571,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-74,,true,,565,161,1,1,null,3,0,0
1542690623062,12,Get Collections,200,OK,Thread Group 1-75,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,12,0,1
1542690623075,9,Get One Collection,200,OK,Thread Group 1-75,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,9,0,0
1542690623060,21,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-75,,true,,1020,365,1,1,null,21,3,1
1542690623084,4,Get Account Info,200,OK,Thread Group 1-75,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690623084,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-75,,true,,565,161,1,1,null,4,0,0
1542690623562,7,Get Collections,200,OK,Thread Group 1-76,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,1
1542690623569,5,Get One Collection,200,OK,Thread Group 1-76,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690623561,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-76,,true,,1020,365,1,1,null,12,1,1
1542690623574,4,Get Account Info,200,OK,Thread Group 1-76,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690623574,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-76,,true,,565,161,1,1,null,4,0,0
1542690624062,13,Get Collections,200,OK,Thread Group 1-77,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690624075,13,Get One Collection,200,OK,Thread Group 1-77,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690624061,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-77,,true,,1020,365,1,1,null,26,2,1
1542690624089,9,Get Account Info,200,OK,Thread Group 1-77,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690624089,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-77,,true,,565,161,1,1,null,9,1,0
1542690624562,12,Get Collections,200,OK,Thread Group 1-78,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,12,0,1
1542690624575,13,Get One Collection,200,OK,Thread Group 1-78,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690624561,25,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-78,,true,,1020,365,1,1,null,25,3,1
1542690624589,9,Get Account Info,200,OK,Thread Group 1-78,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690624589,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-78,,true,,565,161,1,1,null,9,0,0
1542690625063,6,Get Collections,200,OK,Thread Group 1-79,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,6,0,2
1542690625069,5,Get One Collection,200,OK,Thread Group 1-79,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690625062,11,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-79,,true,,1020,365,1,1,null,11,1,2
1542690625074,4,Get Account Info,200,OK,Thread Group 1-79,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690625074,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-79,,true,,565,161,1,1,null,4,0,0
1542690625564,10,Get Collections,200,OK,Thread Group 1-80,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690625574,4,Get One Collection,200,OK,Thread Group 1-80,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690625562,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-80,,true,,1020,365,1,1,null,14,2,1
1542690625579,3,Get Account Info,200,OK,Thread Group 1-80,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690625578,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-80,,true,,565,161,1,1,null,3,1,0
1542690626063,13,Get Collections,200,OK,Thread Group 1-81,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690626076,14,Get One Collection,200,OK,Thread Group 1-81,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690626062,27,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-81,,true,,1020,365,1,1,null,27,1,1
1542690626090,9,Get Account Info,200,OK,Thread Group 1-81,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690626090,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-81,,true,,565,161,1,1,null,9,0,0
1542690626563,10,Get Collections,200,OK,Thread Group 1-82,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690626573,5,Get One Collection,200,OK,Thread Group 1-82,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690626562,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-82,,true,,1020,365,1,1,null,15,1,2
1542690626578,3,Get Account Info,200,OK,Thread Group 1-82,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690626578,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-82,,true,,565,161,1,1,null,3,1,0
1542690627063,10,Get Collections,200,OK,Thread Group 1-83,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,2
1542690627073,5,Get One Collection,200,OK,Thread Group 1-83,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690627062,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-83,,true,,1020,365,1,1,null,15,1,2
1542690627078,4,Get Account Info,200,OK,Thread Group 1-83,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690627078,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-83,,true,,565,161,1,1,null,3,0,0
1542690627563,13,Get Collections,200,OK,Thread Group 1-84,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690627576,13,Get One Collection,200,OK,Thread Group 1-84,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690627562,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-84,,true,,1020,365,1,1,null,26,2,2
1542690627590,8,Get Account Info,200,OK,Thread Group 1-84,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,8,0,0
1542690627590,8,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-84,,true,,565,161,1,1,null,8,1,0
1542690628063,10,Get Collections,200,OK,Thread Group 1-85,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690628074,4,Get One Collection,200,OK,Thread Group 1-85,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690628062,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-85,,true,,1020,365,1,1,null,14,2,1
1542690628078,4,Get Account Info,200,OK,Thread Group 1-85,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690628078,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-85,,true,,565,161,1,1,null,4,0,0
1542690628565,7,Get Collections,200,OK,Thread Group 1-86,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,7,0,3
1542690628572,5,Get One Collection,200,OK,Thread Group 1-86,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690628564,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-86,,true,,1020,365,1,1,null,12,1,3
1542690628577,4,Get Account Info,200,OK,Thread Group 1-86,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690628577,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-86,,true,,565,161,1,1,null,4,0,0
1542690629065,10,Get Collections,200,OK,Thread Group 1-87,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690629075,4,Get One Collection,200,OK,Thread Group 1-87,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690629064,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-87,,true,,1020,365,1,1,null,14,1,1
1542690629079,4,Get Account Info,200,OK,Thread Group 1-87,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690629079,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-87,,true,,565,161,1,1,null,4,0,0
1542690629565,12,Get Collections,200,OK,Thread Group 1-88,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,12,0,1
1542690629577,13,Get One Collection,200,OK,Thread Group 1-88,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690629564,25,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-88,,true,,1020,365,1,1,null,25,1,1
1542690629591,9,Get Account Info,200,OK,Thread Group 1-88,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690629590,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-88,,true,,565,161,1,1,null,9,1,0
1542690630065,13,Get Collections,200,OK,Thread Group 1-89,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,2
1542690630080,9,Get One Collection,200,OK,Thread Group 1-89,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,9,0,0
1542690630064,22,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-89,,true,,1020,365,1,1,null,22,4,2
1542690630090,5,Get Account Info,200,OK,Thread Group 1-89,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,5,0,0
1542690630090,5,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-89,,true,,565,161,1,1,null,5,0,0
1542690630568,13,Get Collections,200,OK,Thread Group 1-90,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690630581,15,Get One Collection,200,OK,Thread Group 1-90,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,15,0,0
1542690630566,28,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-90,,true,,1020,365,1,1,null,28,2,1
1542690630596,10,Get Account Info,200,OK,Thread Group 1-90,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690630596,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-90,,true,,565,161,1,1,null,9,0,0
1542690631066,12,Get Collections,200,OK,Thread Group 1-91,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,12,0,1
1542690631079,13,Get One Collection,200,OK,Thread Group 1-91,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690631065,25,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-91,,true,,1020,365,1,1,null,25,3,1
1542690631093,10,Get Account Info,200,OK,Thread Group 1-91,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,10,0,0
1542690631093,10,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-91,,true,,565,161,1,1,null,10,0,0
1542690631566,10,Get Collections,200,OK,Thread Group 1-92,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690631576,4,Get One Collection,200,OK,Thread Group 1-92,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690631565,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-92,,true,,1020,365,1,1,null,14,1,1
1542690631580,4,Get Account Info,200,OK,Thread Group 1-92,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690631580,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-92,,true,,565,161,1,1,null,4,0,0
1542690632067,10,Get Collections,200,OK,Thread Group 1-93,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690632077,5,Get One Collection,200,OK,Thread Group 1-93,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690632066,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-93,,true,,1020,365,1,1,null,15,1,1
1542690632082,3,Get Account Info,200,OK,Thread Group 1-93,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690632082,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-93,,true,,565,161,1,1,null,3,0,0
1542690632567,13,Get Collections,200,OK,Thread Group 1-94,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690632580,14,Get One Collection,200,OK,Thread Group 1-94,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690632566,27,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-94,,true,,1020,365,1,1,null,27,2,1
1542690632595,9,Get Account Info,200,OK,Thread Group 1-94,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690632595,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-94,,true,,565,161,1,1,null,9,0,0
1542690633068,13,Get Collections,200,OK,Thread Group 1-95,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,13,0,1
1542690633081,13,Get One Collection,200,OK,Thread Group 1-95,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,13,0,0
1542690633067,26,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-95,,true,,1020,365,1,1,null,26,1,1
1542690633095,9,Get Account Info,200,OK,Thread Group 1-95,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690633094,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-95,,true,,565,161,1,1,null,9,2,0
1542690633567,8,Get Collections,200,OK,Thread Group 1-96,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,8,0,2
1542690633575,4,Get One Collection,200,OK,Thread Group 1-96,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690633566,12,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-96,,true,,1020,365,1,1,null,12,2,2
1542690633580,3,Get Account Info,200,OK,Thread Group 1-96,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690633580,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-96,,true,,565,161,1,1,null,3,0,0
1542690634068,10,Get Collections,200,OK,Thread Group 1-97,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690634078,4,Get One Collection,200,OK,Thread Group 1-97,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690634067,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-97,,true,,1020,365,1,1,null,14,1,1
1542690634083,3,Get Account Info,200,OK,Thread Group 1-97,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690634082,3,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-97,,true,,565,161,1,1,null,3,1,0
1542690634567,10,Get Collections,200,OK,Thread Group 1-98,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690634577,4,Get One Collection,200,OK,Thread Group 1-98,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,4,0,0
1542690634566,14,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-98,,true,,1020,365,1,1,null,14,1,1
1542690634581,4,Get Account Info,200,OK,Thread Group 1-98,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,4,0,0
1542690634581,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-98,,true,,565,161,1,1,null,4,0,0
1542690635068,14,Get Collections,200,OK,Thread Group 1-99,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,14,0,2
1542690635082,14,Get One Collection,200,OK,Thread Group 1-99,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,14,0,0
1542690635067,28,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-99,,true,,1020,365,1,1,null,28,1,2
1542690635096,9,Get Account Info,200,OK,Thread Group 1-99,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,9,0,0
1542690635096,9,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-99,,true,,565,161,1,1,null,9,0,0
1542690635568,10,Get Collections,200,OK,Thread Group 1-100,text,true,,535,180,1,1,http://localhost:8888/v1/buckets/default/collections,10,0,1
1542690635578,5,Get One Collection,200,OK,Thread Group 1-100,text,true,,485,185,1,1,http://localhost:8888/v1/buckets/default/collections/Test,5,0,0
1542690635567,15,Colections Controler,200,"Number of samples in transaction : 2, number of failing samples : 0",Thread Group 1-100,,true,,1020,365,1,1,null,15,1,1
1542690635583,4,Get Account Info,200,OK,Thread Group 1-100,text,true,,565,161,1,1,http://localhost:8888/v1/accounts,3,0,0
1542690635583,4,Account Controller,200,"Number of samples in transaction : 1, number of failing samples : 0",Thread Group 1-100,,true,,565,161,1,1,null,3,0,0
