db:
  image: postgres
  environment:
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: 1234567
cache:
  image: redis
web:
  image: kinto/kinto-server
  links:
   - db
   - cache
  ports:
   - "8888:8888"
  volumes:
    - ./config:/etc/kinto
  environment:
    KINTO_CACHE_BACKEND: kinto_redis.cache
    KINTO_CACHE_HOSTS: redis://cache:6379/1
    KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
    KINTO_STORAGE_URL: postgres://testuser:1234567@db/postgres
    KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
    KINTO_PERMISSION_URL: postgres://testuser:1234567@db/postgres
